name: PR Analysis
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: AI Pull Request Analysis
        uses: diekotto/ai-pull-review@v2
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          max_files: '20'
          max_size: '150'
          comment_threshold: '0.7'
          analysis_level: 'standard'
          # model: 'claude-3-5-haiku-20241022'
          file_patterns: |
            **/*.php,
            **/*.module,
            **/*.install,
            **/*.theme,
            **/*.twig,
            **/*.yml,
            **/*.yaml
          exclude_patterns: |
            **/vendor/**,
            **/core/**,
            **/contrib/**,
            **/node_modules/**,
            **/dist/**,
            **/bin/**,
            **/web/libraries/**,
            **/sites/default/files/**

