name: Tests

on:
  pull_request:
    types: [opened, reopened]

env:
  PHP_VERSION: "8.2"
  COMPOSER_VERSION: "2.7.2"

jobs:
  run-phpcs:
    runs-on: ubuntu-latest
    # Disabling the job for Draft pull requests.
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Using our custom composite action to run composer checks and composer install.
      - name: Composer validate and install
        uses: ./.github/actions/composer
        id: composer
        with:
          php_version: ${{ env.PHP_VERSION }}
          composer_version: ${{ env.COMPOSER_VERSION }}

      # Use git diff command to retrieve the list of changed PHP files in the pull request.
      - name: Get modified files
        id: get_files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > files.txt
          cat files.txt

      # We are using phpcs.xml.dist from the project root to determine --extension list, ignores and Drupal,
      # DrupalPractice standards.
      - name: Run PHPCS on Pull Request Files
        run: |
          PHPCS_OUTPUT=$(xargs -a files.txt -r vendor/bin/phpcs --report=checkstyle)

          if [ -n "$PHPCS_OUTPUT" ]; then
            echo "$PHPCS_OUTPUT"
            exit 1
          fi

  run-phpstan:
    runs-on: ubuntu-latest
    # Disabling the job for Draft pull requests.
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Using our custom composite action to run composer checks and composer install.
      - name: Composer validate and install
        uses: ./.github/actions/composer
        id: composer
        with:
          php_version: ${{ env.PHP_VERSION }}
          composer_version: ${{ env.COMPOSER_VERSION }}

      - name: Run PHPStan analysis
        run: vendor/bin/phpstan analyse

  run-phpunit:
    runs-on: ubuntu-latest
    # Disabling the job for Draft pull requests.
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Using our custom composite action to run composer checks and composer install.
      - name: Composer validate and install
        uses: ./.github/actions/composer
        id: composer
        with:
          php_version: ${{ env.PHP_VERSION }}
          composer_version: ${{ env.COMPOSER_VERSION }}

      # We are using phpunit.xml.dist from the project root to determine the directory of the 'Unit' testsuite,
      # in this case 'tests/Unit'.
      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite Unit
