name: Tests

on:
  pull_request:
    types: [opened]

env:
  PHP_VERSION: "8.2"
  COMPOSER_VERSION: "2.7.2"
  PHPCS_EXTENSION_LIST: "php,module,inc,install,test,profile,theme,info,yml"

jobs:
  run-phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/composer.yml

      - uses: php-actions/composer@v6 # We still need to install dependencies in this step.

      - name: Clear Composer cache
        run: composer clear-cache

      - name: Install PHPCS and Drupal Coder
        run: |
          composer global --no-plugins require "squizlabs/php_codesniffer=*"
          composer global --no-plugins require "drupal/coder"

      - name: Set PHPCS Standard
        run: $HOME/.composer/vendor/bin/phpcs --config-set installed_paths $HOME/.composer/vendor/drupal/coder/coder_sniffer/

      # Use git diff command to retrieve the list of changed PHP files in the pull request.

      - name: Run PHPCS on PR Files
        run: |
          PHPCS_OUTPUT=$(git diff --name-only --diff-filter=ACMR -- '*.php' | xargs -r $HOME/.composer/vendor/bin/ --standard=Drupal --extensions=${{ env.PHPCS_EXTENSION_LIST }} --report=checkstyle)

          if [ -n "$PHPCS_OUTPUT" ]; then
            echo "$PHPCS_OUTPUT"
            exit 1
          fi

  run-phpunit:
    runs-on: ubuntu-latest
    needs:
      - setup-php
      - composer-validate
      - composer-install
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6

      - name: Run unit tests
        run: $GITHUB_WORKSPACE/vendor/bin/phpunit --testsuite Unit
