name: Tests

on:
  pull_request:
    types: [opened]

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  setup-php:
    needs: checkout-code
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # PHP version comes from GitHub environment variables.
          extensions: imagick # Only installing to show how to enable extensions.
  
  install-dependencies:
    needs: setup-php
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: composer install # Do we have composer?

  run-phpcs:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check for PHPCS configuration file
        run: |
          if [ ! -f "phpcs.xml.dist" ]; then
            echo "PHPCS configuration file not found."
            exit 1
          fi
      - name: Run PHPCS
        run: |
          vendor/bin/phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,info,yml .

  run-phpstan:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

  run-phpunit:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: PHPUnit tests
        run: vendor/bin/phpunit
