name: Tests

on:
  pull_request:
    types: [opened]

env:
  PHP_VERSION: "8.2"
  COMPOSER_VERSION: "2.7.2"
  PHPCS_EXTENSION_LIST: "php,module,inc,install,test,profile,theme,info,yml"

jobs:
  setup-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

  composer-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json
        run: composer validate --no-check-all

      - name: Check composer.lock
        run: |
          composer install --dry-run
          if [ $? -ne 0 ]; then
            echo "composer.lock is out of date. Please run 'composer update' to generate an updated lock file."
            exit 1
          fi

      - name: Composer cache
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: |
            bin
            vendor
            docroot/core
            docroot/libraries
            docroot/modules/contrib
            docroot/themes/contrib
          key: ${{ runner.os }}-php${{ env.PHP_VERSION }}-composer-${{ env.COMPOSER_VERSION }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies via composer
        if: steps.composer-cache.outputs.cache-hit != 'true'
        uses: "php-actions/composer@v6"
        env:
          COMPOSER: "composer.json"
        with:
          php_version: ${{ env.PHP_VERSION }}
          version: ${{ env.COMPOSER_VERSION }}
          args: "--ignore-platform-reqs --optimize-autoloader"

  run-phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clear Composer cache
        run: composer clear-cache

      - name: Install PHPCS and Drupal Coder
        run: |
          composer global --no-plugins require "squizlabs/php_codesniffer=*"
          composer global --no-plugins require "drupal/coder"

      - name: Set PHPCS Standard
        run: $HOME/.composer/vendor/bin/phpcs --config-set installed_paths $HOME/.composer/vendor/drupal/coder/coder_sniffer/

      # Use git diff command to retrieve the list of changed PHP files in the pull request.

      - name: Run PHPCS on PR Files
        run: |
          PHPCS_OUTPUT=$(git diff --name-only --diff-filter=ACMR -- '*.php' | xargs -r $HOME/.composer/vendor/bin/ --standard=Drupal --extensions=${{ env.PHPCS_EXTENSION_LIST }} --report=checkstyle)

          if [ -n "$PHPCS_OUTPUT" ]; then
            echo "$PHPCS_OUTPUT"
            exit 1
          fi

  run-phpunit:
    runs-on: ubuntu-latest
    needs: setup-php
    steps:
      - name: Install PHPUnit
        run: composer global --no-plugins require "phpunit/phpunit" --dev
      - name: Run unit tests
        run: $HOME/.composer/vendor/bin/phpunit --testsuite Unit
