name: Tests

on:
  push

env:
  PHP_VERSION: "8.2"
  COMPOSER_VERSION: "2.7.2"
  PHPCS_EXTENSION_LIST: "php,module,inc,install,test,profile,theme,info,yml"

jobs:
  run-phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/composer
        id: composer
        with:
          php_version: ${{ env.PHP_VERSION }}
          composer_version: ${{ env.COMPOSER_VERSION }}
      # Clearing cache for autoload_real to be found.
      - name: Clear Composer cache
        run: composer clear-cache

      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite Unit

  run-phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/composer
        id: composer
        with:
          php_version: ${{ env.PHP_VERSION }}
          composer_version: ${{ env.COMPOSER_VERSION }}
      # Clearing cache for autoload_real to be found.
      - name: Clear Composer cache
        run: composer clear-cache

      # Use git diff command to retrieve the list of changed PHP files in the pull request.
      - name: Run PHPCS on PR Files
        run: |
          PHPCS_OUTPUT=$(git diff --name-only --diff-filter=ACMR -- '*.php' | xargs -r vendor/bin/phpcs --report=checkstyle)

          if [ -n "$PHPCS_OUTPUT" ]; then
            echo "$PHPCS_OUTPUT"
            exit 1
          fi
